# Este é um script de implantação mais robusto que instala as ferramentas mais recentes.

name: Deploy to Firebase Hosting and Functions on merge
on:
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Baixa o código do seu repositório
      - uses: actions/checkout@v4

      # 2. Configura a versão correta do Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      # 3. Instala as dependências das Functions
      - name: Install Function Dependencies
        run: npm --prefix functions install

      # 4. Força a instalação da versão mais recente das ferramentas do Firebase
      - name: Install latest Firebase CLI
        run: npm install -g firebase-tools

      # 5. Implanta o Hosting e as Functions usando um comando direto
      - name: Deploy to Firebase
        run: firebase deploy --only hosting,functions --project museu-cca6d --token ${{ secrets.FIREBASE_TOKEN }} --non-interactive

