# Este arquivo foi atualizado para implantar tanto o Hosting quanto as Functions.
# https://github.com/firebase/firebase-tools

name: Deploy to Firebase Hosting and Functions on merge
on:
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Baixa o código do seu repositório
      - uses: actions/checkout@v4

      # 2. Configura o Node.js para instalar as dependências
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18' # Garante que está usando a versão correta do Node.js

      # 3. Instala as dependências das Functions e as ferramentas do Firebase
      - name: Install Dependencies and Firebase Tools
        run: |
          npm --prefix functions install
          npm install -g firebase-tools

      # 4. Implanta as Cloud Functions
      # Este é o passo que estava faltando. Ele usa o FIREBASE_TOKEN que você criou.
      - name: Deploy to Firebase Functions
        run: |
          firebase deploy --only functions --project museu-cca6d --token ${{ secrets.FIREBASE_TOKEN }} --non-interactive
      
      # 5. Implanta o Firebase Hosting (como já fazia antes)
      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_MUSEU_CCA6D }}
          channelId: live
          projectId: museu-cca6d
