# Este arquivo foi atualizado para implantar tanto o Hosting quanto as Functions.
# https://github.com/firebase/firebase-tools

name: Deploy to Firebase Hosting and Functions on merge
on:
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Baixa o código do seu repositório
      - uses: actions/checkout@v4

      # 2. Configura a versão correta do Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      # 3. Instala as dependências das Functions
      - name: Install Function Dependencies
        run: npm --prefix functions install

      # 4. Implanta TUDO (Hosting e Functions) usando a ação oficial do Firebase
      # Esta é uma abordagem mais moderna e confiável
      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_MUSEU_CCA6D }}
          channelId: live
          projectId: museu-cca6d
